# Exercise - Part 2.1 - Python basics

Adapted tutorial from the chapter 3 of the book:

De Ponteves, H. (2019). AI Crash Course: A fun and hands-on introduction to machine learning, reinforcement learning, deep learning, and artificial intelligence with Python. Packt Publishing Ltd.

You can follow original instructions from the link: [chapter 3 tutorial](https://learning.oreilly.com/library/view/ai-crash-course/9781838645359/Text/Chapter_3.xhtml#sigil_toc_id_40)


First, let's try a simple command to display (print) text on the screen, like "Hello world!"

In [1]:
print("Hello world!, test")

Hello world!, test


In Python you can also add comments to describe what your code does or just notes for yourself, starting with '**#**' all after it is not executed as a command

In [2]:
# this is a print
print('Hello world!') # prints Hello world!

Hello world!


**Variables** pointers to values/objects allocated somewhere in the memory. By referring to that variable by defined name, the value/object is retrieved from memory, or a new value is assigned. In Python, you do not need to specify the variable's data type, which is common in languages such Java, C++.

In [3]:
x = 3
y = 5

Here we assign value 3 to variable 'x' and value 5 to variable 'y'. So from this point in code always, as long as you do not change the value, when you refer to variable 'x' it will have value 5 and variable 'y' the value 3

In [4]:
print(f"value in 'x' is {x}")
print("value in 'y' is", y)
print('x + y =', x + y)

value in 'x' is 3
value in 'y' is 5
x + y = 8


Variables can be of different data types, such as integers (2, 3, 4, ...), Float (2.3241213, 4.21), strings ("Hello"), chars ('a', 'b'), and many different objects (arrays, tables, sets of data records). It simplifies your coding by referring to the same data by same-shorter-familiar-reference in the code. You do not want to specify always the array of 1000 records, especially if you will refer to them many times. What you want is to simplify your life and do it once. Thus, you may assign to a variable list of records, for example *my_input_data*

## Lists and Arrays

In [5]:
my_input_data = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]

In Python, you can access the value at a specific index of a list by specifying an index, such as *my_input_data[0]*. Note that indexing in Python starts from 0, last object index is *my_input_data[-1]* or *my_input_data[len(my_input_data) - 1]*, where *len(my_input_data)* is the size of it.

In [6]:
print('first item', my_input_data[0])
print('last item', my_input_data[-1])
print('last item', my_input_data[len(my_input_data) - 1])
print('size of list', len(my_input_data))

first item 0
last item 20
last item 20
size of list 21


You may add new items at the end by calling the list's *append()* function. The item can be deleted by calling the command 'del' and specifying the index.

In [7]:
my_input_data.append(21)
del my_input_data[0]
print(my_input_data)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]


Assign value at certain position

In [8]:
my_input_data[2] = 1000
print(my_input_data)

[1, 2, 1000, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]


## Matrices
In this course, we will often use tables, matrices, or multidimensional matrices. For this, we use *numpy* library. The example below creates the matrix 3x3 filled by zeros.

In [9]:
import numpy as np

matrix_0 = np.zeros((3,3))
print(matrix_0)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Here first index *'x'* of *matrix_0[x,y]* is for rows while second *'y'* is for column of matrix

In [10]:
matrix_0[0,0] = 1
matrix_0[0,1] = 2
matrix_0[0,2] = 3
matrix_0[1,0] = 4
matrix_0[1,1] = 5
matrix_0[1,2] = 6
matrix_0[2,0] = 7
matrix_0[2,1] = 8
matrix_0[2,2] = 9
print(matrix_0)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


Below, we show the calculation of the mean. If you use some function for the first time, checking the documentation, its inputs and outputs, and validating the results is good practice: [mean function definition](https://numpy.org/doc/stable/reference/generated/numpy.mean.html)

In [11]:
matrix_mean = np.mean(matrix_0)
matrix_min = np.min(matrix_0)
matrix_max = np.max(matrix_0)

print(f"The mean of the matrix is {matrix_mean}")
print(f"The min of the matrix is {matrix_min}")
print(f"The max of the matrix is {matrix_max}")

The mean of the matrix is 5.0
The min of the matrix is 1.0
The max of the matrix is 9.0


Changes and copying of objects

In [12]:
matrix_1 = matrix_0.copy() # create new instance of the object which is copied
matrix_2 = matrix_0 # using just assignment command will create only new pointer to existing object, Thus both matrix_0 and matrix_2 point to same object in memory
matrix_2[1,1] = 12 # Thus changing the value will result in change for both matrix_0 and matrix_2 becaue they point to same object.
print('matrix_0',matrix_0)
print('matrix_2',matrix_2)
matrix_1[1,1] = np.nan
print('matrix_0',matrix_0)
print('matrix_1',matrix_1)


matrix_0 [[ 1.  2.  3.]
 [ 4. 12.  6.]
 [ 7.  8.  9.]]
matrix_2 [[ 1.  2.  3.]
 [ 4. 12.  6.]
 [ 7.  8.  9.]]
matrix_0 [[ 1.  2.  3.]
 [ 4. 12.  6.]
 [ 7.  8.  9.]]
matrix_1 [[ 1.  2.  3.]
 [ 4. nan  6.]
 [ 7.  8.  9.]]


In case there are unknown or NaN values in dataset calling np.mean or np.min will fail or result in NaN.

In [13]:
print(np.mean(matrix_1))

nan


An alternative to still calculate a mean value with the remaining values is:

In [14]:
print(np.nanmean(matrix_1))

5.0


Is there any nan value in matrix? use np.isnan()

In [15]:
print(np.isnan(matrix_1))

[[False False False]
 [False  True False]
 [False False False]]


Count them with *np.sum*. Boolean values such True or False they are actully also intepretable as integers: 1:True and 0:False so you can count them.

In [16]:
print(np.sum(np.isnan(matrix_1)))

1


## Constraints IF

Help to branch the code based on logical statements ('AND' and 'OR' and their combinations). For example, if there is a NaN value in the dataset, use a different function to calculate the mean.

In [17]:
if np.sum(np.isnan(matrix_1)) > 0:
  print('there is nan value, np.nanmean calculated',np.nanmean(matrix_1))
else:
 print('there is no nan value, np.mean calculated',np.mean(matrix_1))

there is nan value, np.nanmean calculated 5.0


Another example with more conditions and multiple cases:

In [18]:
if np.sum(np.isnan(matrix_1)) == 0:
  print('there is no nan value, mean is: ',np.mean(matrix_1))
elif np.sum(np.isnan(matrix_1)) > 0 and np.nanmean(matrix_1) < 6:
  print('there is a nan value and the mean is less than 6')
else:
  print('there is a nan value and the mean is greater than or equal to 6')

there is a nan value and the mean is less than 6


## Creating functions
You can create your function to simplify scripts and lower repetitions. If some operations consist of blocks of several lines and would be repeated frequently, the recommended practice is to write the function once and call it when needed. For example, lets define a function for calculating the mean with nan or without nan values.

using above constraints this is how code for calcuting mean for *matrix_0*, *matrix_1*, and *matrix_2* will look:

In [19]:
if np.sum(np.isnan(matrix_0)) > 0:
  print('there is nan value, np.nanmean calculated',np.nanmean(matrix_0))
else:
 print('there is no nan value, np.mean calculated',np.mean(matrix_0))

if np.sum(np.isnan(matrix_1)) > 0:
  print('there is nan value, np.nanmean calculated',np.nanmean(matrix_1))
else:
 print('there is no nan value, np.mean calculated',np.mean(matrix_1))

if np.sum(np.isnan(matrix_2)) > 0:
  print('there is nan value, np.nanmean calculated',np.nanmean(matrix_2))
else:
 print('there is no nan value, np.mean calculated',np.mean(matrix_2))

there is no nan value, np.mean calculated 5.777777777777778
there is nan value, np.nanmean calculated 5.0
there is no nan value, np.mean calculated 5.777777777777778


Or it can be simplify with calling defined function *calculate_mean*

In [20]:
def calculate_mean(input_matrix):
  if np.nansum(np.isnan(input_matrix)) > 0:
    print('there is nan value, np.nanmean calculated',np.nanmean(input_matrix))
  else:
    print('there is no nan value, np.mean calculated',np.mean(input_matrix))

calculate_mean(matrix_0)
calculate_mean(matrix_1)
calculate_mean(matrix_2)

there is no nan value, np.mean calculated 5.777777777777778
there is nan value, np.nanmean calculated 5.0
there is no nan value, np.mean calculated 5.777777777777778


So in this case you can just call function *calculate_mean* and simplify your code

## Loops
These are tools that enable you to iterate across arrays and matrices. For example, we show two different ways of looping with the command *'for'* and print the values of the first row:

In [21]:
for i in range(0, len(matrix_0[0])):
  print('In the first row the value for column ',i+1, matrix_0[0, i])

In the first row the value for column  1 1.0
In the first row the value for column  2 2.0
In the first row the value for column  3 3.0


In [22]:
print(matrix_0)
first_row_in_matrix_0 = matrix_0[0]
i = 1
for value_i in first_row_in_matrix_0:
  print('In the first row the value for column ', i, value_i)
  i +=1

[[ 1.  2.  3.]
 [ 4. 12.  6.]
 [ 7.  8.  9.]]
In the first row the value for column  1 1.0
In the first row the value for column  2 2.0
In the first row the value for column  3 3.0


# Exercise - Part 2.2. - Loading and Exploring External Data

In this part we will load an external data set from a CSV file, explore it with the Python library *pandas* and plot parts of it with the librarby *mathplotlib*.

## Load data with Pandas

Load the library pandas

In [23]:
import pandas as pd

Load the dataset in a pandas DataFrame (similar to a Numpy matrix but offers more functionality)

In [24]:
df = pd.read_csv('Exercise2BusData.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'Exercise2BusData.csv'

If you are not able to upload the data to colab, you can uncommment these lines:

In [ ]:
# url = 'https://raw.githubusercontent.com/zhenliangma/Applied-AI-in-Transportation/master/Exercise_2_regression_model/Exercise2BusData.csv'
# df = pd.read_csv(url)

Exploring the columns and 10 first rows of the DataFrame:

In [ ]:
df.head(10)

## Selecting specific entries

For example, we might be interested in all entries which were to early:

In [ ]:
df[df["Arrival_delay"] < 0]

Combination of filters:

In [ ]:
df[
    (df["Arrival_delay"] < 0)
    & (df["Dwell_time"] > 30)
]

## Analysis of the DataFrame

We can for instance calculate the mean arrival delay for each Bus id:

In [ ]:
df.groupby("Bus_id")["Arrival_delay"].mean()

## Plotting with matplotlib

In [ ]:
import matplotlib.pyplot as plt

We now create a scatter plot plotting the dwell time vs the arrival delay. This can help to uncover relations between the different variables.

In [ ]:
plt.scatter(data=df, x="Dwell_time", y="Arrival_delay")
plt.xlabel("Dwell_time")
plt.ylabel("Arrival_delay")
plt.title("Scatter plot of Dwell Time vs Arrival Delay")
plt.show()

Other plots that might be helpful

In [ ]:
plt.boxplot(df["Dwell_time"])
plt.xlabel("Dwell_time")
plt.title("Box plot of Dwell Time")
plt.show()

# Appendix - Part 1 - Example code that might be helpful for the excersises
In this part, we will focus on a simple example of applying the ML model to transportation prediction applications.

As first lets import, install and upgrade libraries we would need

In [ ]:
# Install packages for colab env
!pip install fastparquet # package for reading .parquet data
!pip install --upgrade geopandas  # for spatial visualization

In [ ]:
import os
import pandas as pd

## Data loading
The below code is pulling the open NY taxi trip data from GitHub repository and create pandas dataframe

In [ ]:
# Loading the dataset
# Two ways to read our data in colab, here we use 2)
# 1). upload
# 2). clone from github repo

"""
# 1). Upload and read data
# import files module
from google.colab import files
uploaded = files.upload()
print(os.listdir())
df = pd.read_parquet('NY_taxi_2017Mar_09-11.parquet', engine='fastparquet')
"""

# 2). Clone and read data from github repo
!git clone https://github.com/georgewanglz2019/Data-Science-and-AI-for-Intelligent-Transport-Systems.git
%cd Data-Science-and-AI-for-Intelligent-Transport-Systems
print(os.listdir())  #  Gets the files and directories present in current path
trips = pd.read_parquet('NY_Taxi_March_2017.parquet', engine='fastparquet')  # extracted trip data

And lets check the dataframe *trips* data by examining first two rows

In [ ]:
trips.head(2) # show the first 10 lines of data

## Modeling
Often, data must be manipulated and processed to the ML model input format. **!!! Note** During the course, you will receive ready datasets or Python scripts for their manipulation to let you focus on exploration and training models. However, you may consider additional manipulation of handling outliers if you identify some in the training process.

### Data manipulation
Here, we want to aggregate the individual trip records to 15 time intervals. They will be used as the historical dataset for training the ML model and predicting future 15 minutes by allowing the use of observations from 3 prior time intervals in the past back to 45 minutes.

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import time
import copy

""" ************************ DATA MANIPULATING/ORGANIZATION ********************************************"""
# I: Calculate passenger trips per time period per day
trips_period = trips.groupby(['DayofYear', 'TimePeriod'])['passenger_count'].sum().reset_index()

# II: construct time series
# step 1: Construct a template of times
time_interval = 15  # 15 min
day_start, day_end = (60, 91)   # March, days starting from January 1
time_start, time_end = (5 * 60, 23 * 60)   # 5:00-23:00 in minutes
unique_days = np.arange(day_start, day_end)
unique_time_periods = np.arange(time_start, time_end, time_interval)   # time period with interval 15 minutes
list_day, list_time = zip(*[(d, t) for d in unique_days for t in unique_time_periods])

ts_template = pd.DataFrame()
ts_template = ts_template.assign(DayofYear=list_day, TimePeriod=list_time)

# step 2: Merge the observations with the template and fill na zero
ts = ts_template.merge(trips_period, on=['DayofYear', 'TimePeriod'], how='left').fillna(0)
ts.sort_values(['DayofYear', 'TimePeriod'], inplace=True, ascending=False)

# step 3: Create columns for time series of pax counts with time lags (t-1, t-2, t-3, etc.)
ts['T'] = ts['passenger_count']
ts['T_1'] = ts['T'].shift(-1)
ts['T_2'] = ts['T'].shift(-2)
ts['T_3'] = ts['T'].shift(-3)
print(ts.head())
# step 4: Delete the record with day transition time periods
del_list = np.arange(time_start, time_start + time_interval * 3, time_interval)

ts = ts[~ts.TimePeriod.isin(del_list)]
print(ts.head())


For training the model, you will need a training set and for testing or evaluating the test dataset's performance. Thus, you have to decide. Here, we pick the first 80 days of the year for training and test the model to predict the later days.

In [ ]:
# step 5: Finalize the data, and split training and testing data
ts_train = ts[ts.DayofYear <= 80]
ts_test = ts[ts.DayofYear > 80]
ts = ts[['T', 'T_1', 'T_2', 'T_3']]

#### Data Exploration
Exploring the data before training is vital for handling missing or outlier values and identifying correlations between features that could be used for predicting others. You may already have experience with such exploration from statistical modeling with linear regression. In this case, correlations between time intervals.

In [ ]:
desc_stat = ts.describe()
desc_stat

In [ ]:
# II. Distribution and scatter plots
sns.pairplot(ts)   # pair plot
plt.show()

In [ ]:
ts_corr = ts.corr()
sns.heatmap(ts_corr)
plt.show()

#### Data preparation for machine learning models
In this example, we consider only two past time-intervals and thus create new sub-sets of train and test data.

In [ ]:
X_train = ts_train[['T_1', 'T_2']]
y_train = ts_train['T']

X_test = ts_test[['T_1', 'T_2']]
y_test = ts_test['T']

In [ ]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error
# train and predict
tree_regressor = DecisionTreeRegressor() # # here we just change parameter 'max_depth'
tree_regressor.fit(X_train, y_train)
y_pred_tree = tree_regressor.predict(X_test)

# compare the prediction and the true value
x = range(len(y_test))
plt.plot(x, y_test, label='True', alpha = 0.7)
plt.plot(x, y_pred_tree, label='Tree Prediciton', alpha = 0.7)
plt.legend()
plt.show()

# evaluation - smaller is better
tree_mse = mean_squared_error(y_test, y_pred_tree)
print(tree_mse)

Always check your ML model to see what parameters need to be calibrated. Check the Decision Tree model and its parameters. [DT model](https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeRegressor.html)

In [ ]:
# Tune the parameters of decision tree, then train and predict
# train and predict
best_t = None
for i in range(1,10):
    tree_regressor = DecisionTreeRegressor(max_depth=i, random_state=45, splitter = 'random') # # here we just change parameter 'max_depth'
    tree_regressor.fit(X_train, y_train)
    y_pred_tree = tree_regressor.predict(X_test)
    # evaluation - smaller is better
    tree_mse = mean_squared_error(y_test, y_pred_tree)
    if best_t is None or best_t > tree_mse:
      best_t = tree_mse
print('best tree mse',best_t)

[RF model](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestRegressor.html#sklearn.ensemble.RandomForestRegressor)

In [ ]:
from sklearn.ensemble import RandomForestRegressor
best_t = None
n_estimators = [10,20,50,100,200,500]
depths = [1,2,5,10,20,30]
for i in range(0,len(depths)-1):
  for j in range(0,len(n_estimators)-1):
    tree_regressor = RandomForestRegressor(max_depth=depths[i], n_estimators = n_estimators[j]) # # here we just change parameter 'max_depth'
    tree_regressor.fit(X_train, y_train)
    y_pred_tree = tree_regressor.predict(X_test)
    # evaluation - smaller is better
    tree_mse = mean_squared_error(y_test, y_pred_tree)
    if best_t is None or best_t > tree_mse:
      best_t = tree_mse
print('best tree mse',best_t)


In [ ]:
best_t = None
#n_estimators = [10,20,50,100,200,500]
#depths = [1,2,5,10,20,30]
for i in range(1,100):
  for j in range(1,20):
    tree_regressor = RandomForestRegressor(max_depth=i, n_estimators = j) # # here we just change parameter 'max_depth'
    tree_regressor.fit(X_train, y_train)
    y_pred_tree = tree_regressor.predict(X_test)
    # evaluation - smaller is better
    tree_mse = mean_squared_error(y_test, y_pred_tree)
    if best_t is None or best_t > tree_mse:
      best_t = tree_mse
print('best tree mse',best_t)

# Appedning - Part 2 - Descriptive statistics and visualizations (for your reference; not covered during exercise)
This part of the appendix gives you an example of visualization and descriptive statistics. It is not covered during the exercise, but you may explore and reuse the code during the course.

Loading additional dataset

In [ ]:
df = pd.read_parquet('NY_taxi_2017Mar_09-11.parquet', engine='fastparquet')

In [ ]:
col_of_interest = ['passenger_count', 'trip_distance', 'fare_amount', 'tip_amount', 'total_amount']
desc_stat_com = df[col_of_interest].describe()
desc_stat_com = desc_stat_com.round(2)   # keep 2 decimals of the float value
desc_stat_com.head(5)  # show the first 5 line of data

### Visualization

Line plot

In [ ]:
plt.style.use('ggplot')  # set visualization style
df['hour'] = pd.to_datetime(df.tpep_pickup_datetime).dt.hour
# get the sum number of each column by hour
df_hour_sum = df.groupby(['hour']).sum()  # refer to https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.groupby.html
df_hour_sum.plot(y=['trip_distance'], kind='line', figsize=(12, 9), legend=True)

Histogram

In [ ]:
df_hour_sum.hist(column=['trip_distance'], figsize=(12, 9), legend=True, bins=20)

Box plot

In [ ]:
df.boxplot(column='passenger_count', by='date', showfliers=True, figsize=(8, 6))

### Spatial visualization

In [ ]:
# refer to https://medium.com/@haonanzhong/new-york-city-taxi-data-analysis-286e08b174a1
# Read in the taxi zone shapefile
import geopandas as gpd
import matplotlib.colors as colors

sf = gpd.read_file('taxi_zones.shp')
sf.head()

In [ ]:
# Compute pickup and dropoff amount of each zone
pu_zone = df.groupby(['PULocationID'], as_index=False).size()  # refer to https://favtutor.com/blogs/pandas-groupby-count
do_zone = df.groupby(['DOLocationID'], as_index=False).size()
pu_zone = gpd.GeoDataFrame(pd.merge(pu_zone, sf, left_on='PULocationID', right_on='LocationID')).drop('LocationID', axis=1)
do_zone = gpd.GeoDataFrame(pd.merge(do_zone, sf, left_on='DOLocationID', right_on='LocationID')).drop('LocationID', axis=1)

In [ ]:
# plot geospatial visualisation to compare pickup and dropoff amount from each zone
fig, axs = plt.subplots(ncols=2, figsize=(20, 10))
fig.subplots_adjust(bottom=0.1, top=0.9, left=0.09, right=0.8, wspace=0.02, hspace=0.02)
# create a normalized colorbar
vmin, vmax = pu_zone['size'].min(), pu_zone['size'].max()
axs[0] = pu_zone.plot(column='size', linewidth=0.09, edgecolor='k', figsize=(10, 10), norm=colors.LogNorm(vmin=vmin, vmax=vmax), cmap='Reds', legend=False, ax=axs[0])
#ctx.add_basemap(axs[0])
vmin, vmax = do_zone['size'].min(), do_zone['size'].max()
axs[1] = do_zone.plot(column='size', linewidth=0.1, edgecolor='k', figsize=(10, 10),
    norm=colors.LogNorm(vmin=vmin, vmax=vmax), cmap='Reds', legend=False, ax=axs[1])
#ctx.add_basemap(axs[1])
axs[0].set_title('Pickup')
axs[1].set_title('Dropoff')
axs[0].set_axis_off()
axs[1].set_axis_off()
# draw the color bar
patch_col = axs[0].collections[0]
cb = fig.colorbar(patch_col, ax=axs, shrink=0.72, orientation="vertical", pad=0.005)
cb.ax.set_ylabel('Trip Amount')
plt.show()